// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddProject(arg1) {
  return window['go']['main']['App']['AddProject'](arg1);
}

export function ArchiveIssue(arg1, arg2) {
  return window['go']['main']['App']['ArchiveIssue'](arg1, arg2);
}

export function BackupDB() {
  return window['go']['main']['App']['BackupDB']();
}

export function BrowseDirectory(arg1) {
  return window['go']['main']['App']['BrowseDirectory'](arg1);
}

export function CheckEnvironment() {
  return window['go']['main']['App']['CheckEnvironment']();
}

export function CheckUpgrade(arg1) {
  return window['go']['main']['App']['CheckUpgrade'](arg1);
}

export function CreateIssue(arg1, arg2, arg3, arg4, arg5, arg6) {
  return window['go']['main']['App']['CreateIssue'](arg1, arg2, arg3, arg4, arg5, arg6);
}

export function CreateTasks(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['CreateTasks'](arg1, arg2, arg3, arg4);
}

export function DeleteIssue(arg1, arg2, arg3) {
  return window['go']['main']['App']['DeleteIssue'](arg1, arg2, arg3);
}

export function DeleteMemoriesBatch(arg1) {
  return window['go']['main']['App']['DeleteMemoriesBatch'](arg1);
}

export function DeleteMemory(arg1) {
  return window['go']['main']['App']['DeleteMemory'](arg1);
}

export function DeleteProject(arg1) {
  return window['go']['main']['App']['DeleteProject'](arg1);
}

export function DeleteTags(arg1, arg2) {
  return window['go']['main']['App']['DeleteTags'](arg1, arg2);
}

export function DeleteTask(arg1, arg2) {
  return window['go']['main']['App']['DeleteTask'](arg1, arg2);
}

export function DeleteTasksByFeature(arg1, arg2) {
  return window['go']['main']['App']['DeleteTasksByFeature'](arg1, arg2);
}

export function DetectPython() {
  return window['go']['main']['App']['DetectPython']();
}

export function ExportMemories(arg1, arg2) {
  return window['go']['main']['App']['ExportMemories'](arg1, arg2);
}

export function GetAppVersion() {
  return window['go']['main']['App']['GetAppVersion']();
}

export function GetArchivedTasks(arg1, arg2) {
  return window['go']['main']['App']['GetArchivedTasks'](arg1, arg2);
}

export function GetCurrentUser(arg1) {
  return window['go']['main']['App']['GetCurrentUser'](arg1);
}

export function GetDBStats() {
  return window['go']['main']['App']['GetDBStats']();
}

export function GetIssueDetail(arg1, arg2) {
  return window['go']['main']['App']['GetIssueDetail'](arg1, arg2);
}

export function GetIssues(arg1, arg2, arg3, arg4, arg5, arg6) {
  return window['go']['main']['App']['GetIssues'](arg1, arg2, arg3, arg4, arg5, arg6);
}

export function GetMemories(arg1, arg2, arg3, arg4, arg5, arg6, arg7) {
  return window['go']['main']['App']['GetMemories'](arg1, arg2, arg3, arg4, arg5, arg6, arg7);
}

export function GetMemoryDetail(arg1) {
  return window['go']['main']['App']['GetMemoryDetail'](arg1);
}

export function GetProjects() {
  return window['go']['main']['App']['GetProjects']();
}

export function GetPythonPath() {
  return window['go']['main']['App']['GetPythonPath']();
}

export function GetSettings() {
  return window['go']['main']['App']['GetSettings']();
}

export function GetStats(arg1) {
  return window['go']['main']['App']['GetStats'](arg1);
}

export function GetStatus(arg1) {
  return window['go']['main']['App']['GetStatus'](arg1);
}

export function GetTags(arg1, arg2) {
  return window['go']['main']['App']['GetTags'](arg1, arg2);
}

export function GetTasks(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['GetTasks'](arg1, arg2, arg3, arg4);
}

export function HealthCheck() {
  return window['go']['main']['App']['HealthCheck']();
}

export function ImportMemories(arg1, arg2) {
  return window['go']['main']['App']['ImportMemories'](arg1, arg2);
}

export function InstallPackage(arg1) {
  return window['go']['main']['App']['InstallPackage'](arg1);
}

export function IsWebDashboardRunning() {
  return window['go']['main']['App']['IsWebDashboardRunning']();
}

export function LaunchWebDashboard() {
  return window['go']['main']['App']['LaunchWebDashboard']();
}

export function ListBackups() {
  return window['go']['main']['App']['ListBackups']();
}

export function Login(arg1, arg2) {
  return window['go']['main']['App']['Login'](arg1, arg2);
}

export function Logout(arg1) {
  return window['go']['main']['App']['Logout'](arg1);
}

export function MergeTags(arg1, arg2, arg3) {
  return window['go']['main']['App']['MergeTags'](arg1, arg2, arg3);
}

export function OpenWebDashboard() {
  return window['go']['main']['App']['OpenWebDashboard']();
}

export function RebuildAllEmbeddings() {
  return window['go']['main']['App']['RebuildAllEmbeddings']();
}

export function Register(arg1, arg2) {
  return window['go']['main']['App']['Register'](arg1, arg2);
}

export function RenameTag(arg1, arg2, arg3) {
  return window['go']['main']['App']['RenameTag'](arg1, arg2, arg3);
}

export function RepairMissingEmbeddings() {
  return window['go']['main']['App']['RepairMissingEmbeddings']();
}

export function RestoreDB(arg1) {
  return window['go']['main']['App']['RestoreDB'](arg1);
}

export function SaveSettings(arg1) {
  return window['go']['main']['App']['SaveSettings'](arg1);
}

export function SearchMemories(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['main']['App']['SearchMemories'](arg1, arg2, arg3, arg4, arg5);
}

export function SelectDirectory() {
  return window['go']['main']['App']['SelectDirectory']();
}

export function SetAutoStart(arg1) {
  return window['go']['main']['App']['SetAutoStart'](arg1);
}

export function SetLanguage(arg1) {
  return window['go']['main']['App']['SetLanguage'](arg1);
}

export function StopWebDashboard() {
  return window['go']['main']['App']['StopWebDashboard']();
}

export function UpdateIssue(arg1, arg2, arg3) {
  return window['go']['main']['App']['UpdateIssue'](arg1, arg2, arg3);
}

export function UpdateMemory(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['UpdateMemory'](arg1, arg2, arg3, arg4);
}

export function UpdateStatus(arg1, arg2, arg3) {
  return window['go']['main']['App']['UpdateStatus'](arg1, arg2, arg3);
}

export function UpdateTask(arg1, arg2, arg3) {
  return window['go']['main']['App']['UpdateTask'](arg1, arg2, arg3);
}
