// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {backup} from '../models';
import {db} from '../models';
import {settings} from '../models';

export function AddProject(arg1:string):Promise<void>;

export function ArchiveIssue(arg1:number,arg2:string):Promise<void>;

export function BackupDB():Promise<backup.BackupInfo>;

export function BrowseDirectory(arg1:string):Promise<Record<string, any>>;

export function CreateIssue(arg1:string,arg2:string,arg3:string,arg4:string,arg5:Array<string>,arg6:number):Promise<Record<string, any>>;

export function CreateTasks(arg1:string,arg2:string,arg3:string,arg4:string):Promise<number>;

export function DeleteIssue(arg1:number,arg2:string,arg3:boolean):Promise<void>;

export function DeleteMemoriesBatch(arg1:Array<string>):Promise<number>;

export function DeleteMemory(arg1:string):Promise<void>;

export function DeleteProject(arg1:string):Promise<number>;

export function DeleteTags(arg1:string,arg2:Array<string>):Promise<number>;

export function DeleteTask(arg1:number,arg2:string):Promise<void>;

export function DeleteTasksByFeature(arg1:string,arg2:string):Promise<number>;

export function DetectPython():Promise<string>;

export function ExportMemories(arg1:string,arg2:string):Promise<Array<db.MemoryExport>>;

export function GetArchivedTasks(arg1:string,arg2:string):Promise<Array<db.TaskGroup>>;

export function GetDBStats():Promise<db.DBStats>;

export function GetIssueDetail(arg1:number,arg2:string):Promise<db.Issue>;

export function GetIssues(arg1:string,arg2:string,arg3:string,arg4:string,arg5:number,arg6:number):Promise<db.IssueListResult>;

export function GetMemories(arg1:string,arg2:string,arg3:string,arg4:string,arg5:string,arg6:number,arg7:number):Promise<db.MemoryListResult>;

export function GetMemoryDetail(arg1:string):Promise<db.Memory>;

export function GetProjects():Promise<Array<db.Project>>;

export function GetPythonPath():Promise<string>;

export function GetSettings():Promise<settings.Settings>;

export function GetStats(arg1:string):Promise<Record<string, any>>;

export function GetStatus(arg1:string):Promise<db.SessionState>;

export function GetTags(arg1:string,arg2:string):Promise<Array<db.TagInfo>>;

export function GetTasks(arg1:string,arg2:string,arg3:string,arg4:string):Promise<Array<db.TaskGroup>>;

export function HealthCheck():Promise<db.HealthReport>;

export function ImportMemories(arg1:string,arg2:string):Promise<Record<string, number>>;

export function IsWebDashboardRunning():Promise<boolean>;

export function LaunchWebDashboard():Promise<void>;

export function ListBackups():Promise<Array<backup.BackupInfo>>;

export function MergeTags(arg1:string,arg2:Array<string>,arg3:string):Promise<number>;

export function RebuildAllEmbeddings():Promise<void>;

export function RenameTag(arg1:string,arg2:string,arg3:string):Promise<number>;

export function RepairMissingEmbeddings():Promise<void>;

export function RestoreDB(arg1:string):Promise<void>;

export function SaveSettings(arg1:settings.Settings):Promise<void>;

export function SearchMemories(arg1:string,arg2:string,arg3:string,arg4:Array<string>,arg5:number):Promise<Array<db.Memory>>;

export function SelectDirectory():Promise<string>;

export function SetLanguage(arg1:string):Promise<void>;

export function SetAutoStart(arg1:boolean):Promise<void>;

export function StopWebDashboard():Promise<void>;

export function UpdateIssue(arg1:number,arg2:string,arg3:string):Promise<db.Issue>;

export function UpdateMemory(arg1:string,arg2:string,arg3:Array<string>,arg4:string):Promise<db.Memory>;

export function UpdateStatus(arg1:string,arg2:string,arg3:Array<string>):Promise<db.SessionState>;

export function UpdateTask(arg1:number,arg2:string,arg3:string):Promise<db.Task>;
